#!/bin/bash

# 1. Update
apt update -y

# 2. Install Java
apt install -y openjdk-17-jdk

# 3. Install curl
apt install -y curl

# 4. Install NVM for ubuntu user
sudo -u ubuntu bash << 'EOF'
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm install 24

echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc
echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.bashrc
EOF
